---
label: Services
hide_body: false
fields:
- type: datetime
  name: date
  label: date
- type: text
  name: description
  label: description
- type: file
  name: featured_image
  label: featured_image
- type: text
  name: ogdescription
  label: ogdescription
- type: text
  name: ogtitle
  label: ogtitle
- type: text
  name: summary
  label: summary
- type: text
  name: title
  label: title
- type: text
  name: twitterdescription
  label: twitterdescription
- type: text
  name: twittertitle
  label: twittertitle
- name: hero_image
  type: file
  config:
    maxSize: 250
  label: Hero Image
