baseurl = "/"
languageCode = "en-us"
languageLang = "en"
paginate = 3
title = "¦¦ Pixaful"
[[menu.mainmenu]]
name = "Online Marketing"
parent = "What I do"
url = "#"
weight = 4
[[menu.mainmenu]]
name = "Website Maintenance"
parent = "What I do"
url = "#"
weight = 3
[[menu.mainmenu]]
name = "Website Security"
parent = "What I do"
url = "#"
weight = 2
[[menu.mainmenu]]
name = "Website Development"
parent = "What I do"
url = "#"
weight = 1
[[menu.mainmenu]]
identifyer = "home"
name = "Home"
url = "/"
weight = 1
[[menu.mainmenu]]
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]
identifyer = "Blog"
name = "Blog"
url = "/blog"
weight = 4
[[menu.mainmenu]]
name = "What I do"
url = "#"
weight = 3
[params.tiles]
enable = true
[[params.tiles.showcase]]
image = "pic01.jpg"
subtitle = "Ipsum Dolor Sit Amet"
title = "Aliquam"
url = "blogs/aliquam"
[[params.tiles.showcase]]
image = "pic02.jpg"
subtitle = "Feugiat Amet Tempus"
title = "Tempus"
url = "blogs/tempus"
