baseurl = "/"
languageCode = "en-us"
languageLang = "en"
paginate = 3
title = "¦¦ Pixaful"
[[menu.mainmenu]]
name = "Website Security"
parent = "What I do"
url = "/services/website-security/"
weight = 6
[[menu.mainmenu]]
name = "Website Maintenance"
parent = "What I do"
url = "/services/website-maintenance"
weight = 5
[[menu.mainmenu]]
name = "Website Consultation"
parent = "What I do"
url = "/services/website-consultation/"
weight = 4
[[menu.mainmenu]]
name = "Website Development"
parent = "What I do"
url = "/services/web-development/"
weight = 3
[[menu.mainmenu]]
name = "Search Engine Optimisation"
parent = "What I do"
url = "/services/search-engine-optimisation/"
weight = 2
[[menu.mainmenu]]
name = "E-Commerce Development"
parent = "What I do"
url = "/services/ecommerce-development/"
weight = 1
[[menu.mainmenu]]
name = "Portfolio"
url = "#"
weight = 3
[[menu.mainmenu]]
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]
identifyer = "Blog"
name = "Blog"
url = "/blog"
weight = 4
[[menu.mainmenu]]
name = "What I do"
url = "#"
weight = 2
[[menu.mainmenu]]
identifyer = "home"
name = "Home"
url = "/"
weight = 1
[params]
cloudinary_base_url = "https://res.cloudinary.com/pixaful/image/upload"
[params.tiles]
enable = true
[[params.tiles.showcase]]
image = "pic01.jpg"
subtitle = "Ipsum Dolor Sit Amet"
title = "Aliquam"
url = "blogs/aliquam"
[[params.tiles.showcase]]
image = "pic02.jpg"
subtitle = "Feugiat Amet Tempus"
title = "Tempus"
uglyurls = true
url = "blogs/tempus"
[permalinks]
post = ":filename"
[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
cache-control = "\tmax-age=0,\n\tno-cache,\n\tno-store,\n\tmust-revalidate"

[[headers]]
  for = "*.js" # js files should be set this way
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "*.css" # css files too
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "*.png" # js files should be set this way
  [headers.values]
    Cache-Control = "public, max-age=604800"
